agents:
  queue: release
_templates:
  common: &common
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2
    # This is enforced by the environment hooks on the release agents
    # as well, only the master branch may be built there.
    if: build.branch == "master" || build.tag != null

steps:
  - <<: *common
    label: ":ship: Push all images (x86_64)"
    commands:
      - make ARCH=x86_64 push-all-images
  - <<: *common
    label: ":ship: Push all images (aarch64)"
    commands:
      - make ARCH=aarch64 push-all-images
  - <<: *common
    label: ":ship: Release"
    commands:
      - make BAZEL_OPTIONS=--config=x86_64 artifacts/x86_64
      - make BAZEL_OPTIONS=--config=aarch64 artifacts/aarch64
      - make release RELEASE_NIGHTLY=$$RELEASE_NIGHTLY
      - cd repo && gsutil cp -r . gs://gvisor/releases/
  - <<: *common
    label: ":ship: Kythe"
    if: build.tag == null # Don't build tags.
    commands:
      - make kythe-index
      - gsutil cp *.kzip gs://gvisor-kythe-xrefs
  - <<: *common
    label: ":ship: Website Deploy"
    commands:
      # The built website image must be x86_64.
      - make BAZEL_OPTIONS=--config=x86_64 website-deploy
